#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Oleg Fedorov
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

OUTPUT		=	fortune
OBJECTS		=	fortune.o
LDLIBS		=	-\( -lc -lcpp -lfos -\)
TARGETDIR	=	$(INITRDDIR)/usr/bin

include $(SYSTEM_SRC)/mk/trg_bin_std.mk

