#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Oleg Fedorov
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

INSTALLDIR	=	$(LIB)
OUTPUT		=	libfgs.a
OBJECTS		=	GUIInit.o 	CreateWindow.o	\
			WaitEvent.o 	DestroyWindow.o	\
			RefreshWindow.o	GuiEnd.o 	\
			pixel.o		rect.o		\
			pstring.o	line.o		\
			SetVisible.o	ControlsWindow.o 	\
			MessageLoop.o	drawing.o	\
			Controls.o	ScreenInfo.o	\
			GetDrawingHandle.o		\
			WindowShift.o

include $(SYSTEM_SRC)/mk/trg_lib.mk

