#!/bin/sh

TIMER=`cat /proc/sys/dev/rtc/max-user-freq`

if  (($TIMER < 1024));
then
    cat <<EOF
———————————————————————————————————————————————————————————————————————————————
ВНИМАНИЕ!!
 Частота таймера ниже 1024Гц! Эмулятор будет работать некорректно!

 Выполни от рута команду «echo "1024" > /proc/sys/dev/rtc/max-user-freq» для 
правильной работы.
———————————————————————————————————————————————————————————————————————————————
EOF
fi

qemu -net none -boot d -localtime -cdrom FOS-current.iso -m 32 -serial stdio
