#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Oleg Fedorov
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

INSTALLDIR	=	$(LIB)
OUTPUT		=	crt0.o
OBJECTS		=	crt0.o

include $(SYSTEM_SRC)/mk/trg_obj.mk


