# -----------------------------------------------------------------------------
# Copyright (C) 2006-2007 Oleg Fedorov
# -----------------------------------------------------------------------------

include $(ROOT)/config.mk
include $(SYSTEM_SRC)/mk/subdir.mk

ITEMS = crt0 int16b libc libcpp libfos libgwinsy libpci $(wildcard freetype-2.3.5)
