#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Oleg Fedorov
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

INSTALLDIR	=	$(LIB)
OUTPUT		=	libcpp.a

OBJECTS		=	libcpp.o

include $(SYSTEM_SRC)/mk/trg_lib.mk

