#----------------------------------------------------------------------------#
#  Copyright (c) 2008 Gridassov Sergey
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk
OUTPUT		=	rtc

OBJECTS		=	rtc.o

LDLIBS		=	-\( -lcpp -lc -lfos -\)

TARGETDIR	=	$(INITRDDIR)/bin

include $(SYSTEM_SRC)/mk/trg_bin_std.mk

