#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Oleg Fedorov
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

OUTPUT		=	test
OBJECTS		=	main.o
LDLIBS		=	-\( -lc -lcpp -lfos -lfgs -\)
TARGETDIR	=	$(INITRDDIR)/usr/bin

include $(SYSTEM_SRC)/mk/trg_bin_std.mk

