#!/bin/bash
echo FOS ports

mkdir -p installed
mkdir -p tarballs

echo -n "Updating package list: "

rm -f packages.lst

if wget http://grindars.org.ru/fosports/packages.lst; then
	echo ok
else
	echo failed.
	exit 1
fi

cat packages.lst | while read fn; do
	if [ ! -e installed/$fn ]; then
		echo "Installing package $fn"
		if [ ! -e tarballs/$fn.tar.bz2 ]; then
			echo -n " Downloading precompiled tarball: "
			if wget http://grindars.org.ru/fosports/precompiled/$fn.tar.bz2 -O tarballs/$fn.tar.bz2 ; then
				echo ok
			else
				echo failed.
				rm -f tarballs/$fn.tar.bz2
				exit 1
			fi
		fi
		echo -n " Decompressing tarball: "
		if tar xjf tarballs/$fn.tar.bz2 -C `pwd`/..; then
			echo ok
		else
			echo failed
			exit 1;
		fi
		touch installed/$fn
	fi
done