#----------------------------------------------------------------------------#
#	Copyright (C) 2008 Gridassov Sergey
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

OUTPUT		=	pcid

OBJECTS		=	main.o pci.o

LDLIBS		=	-\( -lc -lcpp -lfos -\)

TARGETDIR	=	$(INITRDDIR)/bin

include $(SYSTEM_SRC)/mk/trg_bin_std.mk

