#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Gridassov Sergey
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

OUTPUT		=	romfs

OBJECTS		=	main.o romfs.o

LDLIBS		=	-\( -lc -lcpp -lfos -\)

TARGETDIR	=	$(INSTALLDIR)

include $(SYSTEM_SRC)/mk/trg_bin_std.mk

