#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Gridassov Sergey
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

OUTPUT		=	tmpfs

OBJECTS		=	main.o tmpfs.o

LDLIBS		=	-\( -lc -lcpp -lfos -\)

TARGETDIR	=	$(INITRDDIR)/bin

include $(SYSTEM_SRC)/mk/trg_bin_std.mk

