#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Oleg Fedorov
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

OUTPUT		=	init
OBJECTS		=	init.o
LDLIBS		=	-\( -lc -lcpp -lfos -\)
TARGETDIR	=	$(INSTALLDIR)

include $(SYSTEM_SRC)/mk/trg_bin_std.mk

