#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Oleg Fedorov
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

INSTALLDIR	=	$(LIB)

OUTPUT		=	libpci.a

OBJECTS		=	pci_outb.o	pci_outw.o	\
			pci_outl.o	pci_inb.o	\
			pci_inw.o	pci_inl.o	\
			pci_check.o

include $(SYSTEM_SRC)/mk/trg_lib.mk

