# -----------------------------------------------------------------------------
# Copyright (C) 2006-2007 Oleg Fedorov
# -----------------------------------------------------------------------------

include $(ROOT)/config.mk
include $(SYSTEM_SRC)/mk/subdir.mk

ITEMS = init ipctest shell fortune coreutils pci_scan test2 fontconfig-tools
