#
# Portable Graphics System
#       GUI system
# Copyright (c) 2007 Grindars
include config.mk

CFLAGS=-I../include --std=c99 $(shell sdl-config --cflags)
CC=gcc

all: $(OBJECTS_AL)
clean:
	rm -f $(OBJECTS_AL)