#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Oleg Fedorov
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

INSTALLDIR	=	$(LIB)
OUTPUT		=	libfos.a
OBJECTS		=	message.o		\
			kill.o			\
			exec.o			\
			kmmap.o			\
			kmunmap.o		\
			getpagephysaddr.o	\
			thcreate.o		\
			intattach.o		\
			intdetach.o		\
			resmgrattach.o		\
			dmesg.o			\
			uptime.o		\
			alarm.o			\
			alarm2.o		\
			mytid.o			\
			get_time.o		\
			nsi.o			\
			nsi_c.o

include $(SYSTEM_SRC)/mk/trg_lib.mk
