#----------------------------------------------------------------------------#
#	Copyright (C) 2007 Oleg Fedorov
#----------------------------------------------------------------------------#

include $(ROOT)/config.mk

INSTALLDIR	=	$(LIB)
OUTPUT		=	libc.a
OBJECTS		=	close.o		malloc.o	\
			exit.o		lseek.o		\
			open.o		read.o		\
			write.o		sprintf.o	\
			vsprintf.o	printf.o	\
			time.o		stat.o		\
			fstat.o		strspn.o	\
			strcspn.o	strtok_r.o 	\
			strsep.o	random.o 	\
			opendir.o	getopt.o 	\
			readdir.o	closedir.o	\
			rewinddir.o	seekdir.o 	\
			telldir.o	strtoul.o	\
			__add_to_environ.o		\
			setenv.o	unsetenv.o	\
			getenv.o	getcwd.o	\
			fgets.o		chdir.o		\
			putenv.o	realpath.o

include $(SYSTEM_SRC)/mk/trg_lib.mk

