# -----------------------------------------------------------------------------
# Copyright (C) 2006-2008 Oleg Fedorov
# -----------------------------------------------------------------------------

include $(ROOT)/config.mk
include $(SYSTEM_SRC)/mk/subdir.mk

ITEMS = namer gwinsy tty i8042 stty romfs rtc tmpfs pci 
# $(wildcard net2)